# Generated by Django 3.2.3 on 2021-06-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
